//#if 0
//K9F8G08
#define PAGE_SIZE 4096
#define PAGES_IN_BLOCK 64
#define NAND_SECTORS_COUNT_COEFF 2 //NAND_SIZE_COEFF = NAND_FLASH_SIZE / 512MB
//#else
//K9F4G08
//#define PAGE_SIZE 2048
//#define PAGES_IN_BLOCK 64
//#define NAND_SECTORS_COUNT_COEFF 1
//#endif

#define SECTORS_IN_PAGE (PAGE_SIZE/512)
#define BAD_BLOCKS_LIST_SIZE 80