@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM 


"E:\PROGRAMS\IAR_ARM_6.20_EW\common\bin\cspybat" "E:\PROGRAMS\IAR_ARM_6.20_EW\arm\bin\armproc.dll" "E:\PROGRAMS\IAR_ARM_6.20_EW\arm\bin\armjlink.dll"  %1 --plugin "E:\PROGRAMS\IAR_ARM_6.20_EW\arm\bin\armbat.dll" --macro "E:\Sasho\PROJECTS\LPC-H3131\demos\AudioDevice\config\LPC313x_SDRAM.mac" --backend -B "--endian=little" "--cpu=ARM926EJ-S" "--fpu=None" "-p" "E:\PROGRAMS\IAR_ARM_6.20_EW\arm\CONFIG\debugger\NXP\iolpc3130.ddf" "--drv_verify_download" "--semihosting" "--device=LPC3131" "--drv_communication=USB0" "--jlink_speed=1000" "--drv_catch_exceptions=0x000" 


